import type { Repertoire, Field } from './common.ts'
import {
  SEP, text, richText, itemsJoin, directJoin,
  juryActif, juryComposition, statistiquesPromotions, publicationDecret, correspondances,
  DATASET_DESCRIPTION
} from './common.ts'

// Résumé repris tel quel de la prod (koumoul.com/.../competences-rncp), utilisé à la création.
const DATASET_SUMMARY = 'Le jeu RNCP (Répertoire National des Certifications Professionnelles) liste les diplômes et titres reconnus par l’État français. Géré par France Compétences, il recense niveaux, secteurs, organismes certificateurs et validité des certifications pour orienter professionnels et employeurs.'

const schema: Field[] = [
  // ---- Colonnes historiques (ordre conservé pour la stabilité du jeu de données) ----
  { key: 'ID_FICHE', type: 'integer', title: 'Identifiant de fiche', description: 'Identifiant numérique interne de la fiche chez France compétences, stable dans le temps et utilisé pour relier les fiches entre elles.', extract: (f) => text(f, 'ID_FICHE') },
  { key: 'NUMERO_FICHE', type: 'string', title: 'Numéro de fiche', description: 'Code public de la certification, préfixé « RNCP » pour le Répertoire national des certifications professionnelles (ex. RNCP38362).', extract: (f) => text(f, 'NUMERO_FICHE') },
  { key: 'INTITULE', type: 'string', title: 'Intitulé', description: 'Intitulé officiel de la certification tel qu’enregistré par France compétences.', 'x-refersTo': 'http://www.w3.org/2000/01/rdf-schema#label', extract: (f) => text(f, 'INTITULE') },
  { key: 'ABREGE_CODES', type: 'string', title: 'Abrégé (code)', description: 'Sigle ou forme abrégée de la certification, lorsqu’il existe (ex. BTS, BUT, LP).', separator: SEP, extract: (f) => directJoin(f, 'ABREGE', 'CODE') },
  { key: 'ABREGE_LIBELLES', type: 'string', title: 'Abrégé (libellé)', description: 'Libellé développé correspondant au sigle de la certification.', extract: (f) => directJoin(f, 'ABREGE', 'LIBELLE') },
  { key: 'ETAT_FICHE', type: 'string', title: 'État de la fiche', description: 'Statut de la fiche : « Publiée » (active et consultable), « Dépubliée/Archivée », ou en cours de modification.', enum: ['Publiée', 'Dépubliée/Archivée', 'Modifications à valider', 'Modifications à valider par le ministère'], extract: (f) => text(f, 'ETAT_FICHE') },
  { key: 'NOMENCLATURE_EUROPE_NIVEAU', type: 'string', title: 'Niveau de qualification', description: 'Niveau de qualification au cadre national des certifications professionnelles, de 3 à 8 (aligné sur le cadre européen des certifications).', separator: SEP, extract: (f) => directJoin(f, 'NOMENCLATURE_EUROPE', 'NIVEAU') },
  { key: 'NOMENCLATURE_EUROPE_INTITULE', type: 'string', title: 'Intitulé du niveau', description: 'Libellé du niveau de qualification (ex. « Niveau 5 »).', separator: SEP, extract: (f) => directJoin(f, 'NOMENCLATURE_EUROPE', ['LIBELLE', 'INTITULE']) },
  { key: 'TYPE_EMPLOI_ACCESSIBLES', type: 'string', title: 'Types d’emploi accessibles', description: 'Métiers et types d’emploi accessibles aux titulaires de la certification.', 'x-display': 'markdown', extract: (f) => richText(f, 'TYPE_EMPLOI_ACCESSIBLES') },
  { key: 'CODES_ROME', type: 'string', title: 'Codes ROME', description: 'Codes ROME (répertoire opérationnel des métiers et des emplois, France Travail) associés à la certification.', separator: SEP, extract: (f) => itemsJoin(f, 'CODES_ROME', 'ROME', 'CODE') },
  { key: 'LIBELLES_ROME', type: 'string', title: 'Libellés ROME', description: 'Libellés des métiers ROME correspondant aux codes ROME.', separator: SEP, extract: (f) => itemsJoin(f, 'CODES_ROME', 'ROME', ['LIBELLE', 'INTITULE']) },
  { key: 'CODES_NSF', type: 'string', title: 'Codes NSF', description: 'Codes de la Nomenclature des spécialités de formation (NSF) situant la certification par domaine.', separator: SEP, extract: (f) => itemsJoin(f, 'CODES_NSF', 'NSF', 'CODE') },
  { key: 'INTITULE_NSF', type: 'string', title: 'Intitulés NSF', description: 'Libellés des spécialités de formation (NSF) correspondant aux codes NSF.', separator: SEP, extract: (f) => itemsJoin(f, 'CODES_NSF', 'NSF', ['LIBELLE', 'INTITULE']) },
  { key: 'CERTIFICATEURS', type: 'string', title: 'Certificateurs', description: 'Raisons sociales des organismes habilités à délivrer la certification ; alignées avec la colonne SIRET des certificateurs.', separator: SEP, extract: (f) => itemsJoin(f, 'CERTIFICATEURS', 'CERTIFICATEUR', 'NOM_CERTIFICATEUR') },
  { key: 'ACTIVITES_VISEES', type: 'string', title: 'Activités visées', description: 'Activités professionnelles que la certification permet d’exercer.', 'x-display': 'markdown', extract: (f) => richText(f, 'ACTIVITES_VISEES') },
  { key: 'CAPACITES_ATTESTEES', type: 'string', title: 'Compétences attestées', description: 'Compétences et capacités que la certification atteste, telles que décrites dans la fiche.', 'x-display': 'markdown', extract: (f) => richText(f, 'CAPACITES_ATTESTEES') },
  { key: 'LIEN_URL_DESCRIPTION', type: 'string', title: 'Lien vers le descriptif', description: 'URL de la page officielle décrivant la certification sur le site de France compétences.', 'x-refersTo': 'https://schema.org/WebPage', extract: (f) => richText(f, 'LIEN_URL_DESCRIPTION') },
  { key: 'REGLEMENTATIONS_ACTIVITES', type: 'string', title: 'Réglementations d’activités', description: 'Réglementations encadrant l’exercice des activités visées (habilitations, autorisations, conditions légales), le cas échéant.', 'x-display': 'markdown', extract: (f) => richText(f, 'REGLEMENTATIONS_ACTIVITES') },
  { key: 'OBJECTIFS_CONTEXTE', type: 'string', title: 'Objectifs et contexte', description: 'Objectifs de la certification et contexte professionnel dans lequel elle s’inscrit.', 'x-display': 'markdown', 'x-refersTo': 'http://schema.org/description', extract: (f) => richText(f, 'OBJECTIFS_CONTEXTE') },
  { key: 'SI_JURY_FI', type: 'boolean', title: 'Voie d’accès : formation initiale', description: 'Certification accessible par un parcours de formation initiale sous statut d’élève ou d’étudiant.', extract: (f) => juryActif(f, 'SI_JURY_FI') },
  { key: 'JURY_FI', type: 'string', title: 'Jury — formation initiale', description: 'Composition du jury de certification pour la voie de la formation initiale.', 'x-display': 'markdown', extract: (f) => juryComposition(f, 'SI_JURY_FI') },
  { key: 'SI_JURY_CA', type: 'boolean', title: 'Voie d’accès : apprentissage', description: 'Certification accessible en contrat d’apprentissage.', extract: (f) => juryActif(f, 'SI_JURY_CA') },
  { key: 'JURY_CA', type: 'string', title: 'Jury — apprentissage', description: 'Composition du jury de certification pour la voie de l’apprentissage.', 'x-display': 'markdown', extract: (f) => juryComposition(f, 'SI_JURY_CA') },
  { key: 'SI_JURY_FC', type: 'boolean', title: 'Voie d’accès : formation continue', description: 'Certification accessible après un parcours de formation continue.', extract: (f) => juryActif(f, 'SI_JURY_FC') },
  { key: 'SI_JURY_CQ', type: 'boolean', title: 'Voie d’accès : contrat de professionnalisation', description: 'Certification accessible en contrat de professionnalisation.', extract: (f) => juryActif(f, 'SI_JURY_CQ') },
  { key: 'SI_JURY_CL', type: 'boolean', title: 'Voie d’accès : candidature individuelle', description: 'Certification accessible par candidature individuelle, hors parcours de formation.', extract: (f) => juryActif(f, 'SI_JURY_CL') },
  { key: 'JURY_CL', type: 'string', title: 'Jury — candidature individuelle', description: 'Composition du jury de certification pour la voie de la candidature individuelle.', 'x-display': 'markdown', extract: (f) => juryComposition(f, 'SI_JURY_CL') },
  { key: 'SI_JURY_VAE', type: 'boolean', title: 'Voie d’accès : VAE', description: 'Certification accessible par la validation des acquis de l’expérience (VAE).', extract: (f) => juryActif(f, 'SI_JURY_VAE') },
  { key: 'ACTIF', type: 'boolean', title: 'Active', description: 'Indique si la certification est active (enregistrement en cours de validité) ou inactive.', extract: (f) => text(f, 'ACTIF') },

  // ---- Colonnes ajoutées (flux V4-1, non destructif) ----
  { key: 'jury_fc', type: 'string', title: 'Jury — formation continue', description: 'Composition du jury de certification pour la voie de la formation continue.', 'x-display': 'markdown', extract: (f) => juryComposition(f, 'SI_JURY_FC') },
  { key: 'jury_cq', type: 'string', title: 'Jury — contrat de professionnalisation', description: 'Composition du jury de certification pour la voie du contrat de professionnalisation.', 'x-display': 'markdown', extract: (f) => juryComposition(f, 'SI_JURY_CQ') },
  { key: 'jury_vae', type: 'string', title: 'Jury — VAE', description: 'Composition du jury de certification pour la voie de la VAE.', 'x-display': 'markdown', extract: (f) => juryComposition(f, 'SI_JURY_VAE') },
  { key: 'formacodes', type: 'string', title: 'Codes Formacode', description: 'Codes Formacode® (thésaurus du Centre Inffo) des domaines de formation couverts par la certification.', separator: SEP, extract: (f) => itemsJoin(f, 'FORMACODES', 'FORMACODE', 'CODE') },
  { key: 'formalibelles', type: 'string', title: 'Libellés Formacode', description: 'Libellés des domaines de formation correspondant aux codes Formacode®.', separator: SEP, extract: (f) => itemsJoin(f, 'FORMACODES', 'FORMACODE', 'LIBELLE') },
  { key: 'secteurs_activite', type: 'string', title: 'Secteurs d’activités', description: 'Secteurs d’activité économique dans lesquels s’exercent les métiers visés par la certification.', 'x-display': 'markdown', extract: (f) => richText(f, 'SECTEURS_ACTIVITE') },
  { key: 'type_enregistrement', type: 'string', title: 'Type d’enregistrement', description: 'Modalité d’enregistrement : « de droit » (relevant d’un ministère) ou « sur demande » (après instruction par France compétences).', enum: ['Enregistrement de droit', 'Enregistrement sur demande'], extract: (f) => text(f, 'TYPE_ENREGISTREMENT') },
  { key: 'date_decision', type: 'string', title: 'Date de décision', description: 'Date de la décision d’enregistrement de la certification par France compétences.', extract: (f) => text(f, 'DATE_DECISION') },
  { key: 'date_effet', type: 'string', title: 'Date d’effet', description: 'Date d’effet du dernier arrêté ou de la dernière décision concernant la certification.', 'x-refersTo': 'https://schema.org/startDate', extract: (f) => text(f, 'DATE_EFFET') },
  { key: 'date_fin_enregistrement', type: 'string', title: 'Date de fin d’enregistrement', description: 'Date d’échéance de l’enregistrement au répertoire ; au-delà, la certification ne peut plus être délivrée (sauf date limite de délivrance distincte).', 'x-refersTo': 'https://schema.org/endDate', extract: (f) => text(f, 'DATE_FIN_ENREGISTREMENT') },
  { key: 'date_dernier_jo', type: 'string', title: 'Date du dernier JO', description: 'Date de la dernière parution au Journal officiel (JO) ou Bulletin officiel (BO) concernant la certification.', extract: (f) => text(f, 'DATE_DERNIER_JO') },
  { key: 'duree_enregistrement', type: 'string', title: 'Durée d’enregistrement', description: 'Durée de l’enregistrement de la certification au répertoire, exprimée en années.', extract: (f) => text(f, 'DUREE_ENREGISTREMENT') },
  { key: 'existence_partenaires', type: 'boolean', title: 'Existence de partenaires', description: 'Indique si des organismes partenaires sont habilités à préparer ou délivrer la certification (voir colonnes Partenaires).', extract: (f) => text(f, 'EXISTENCE_PARTENAIRES') },
  { key: 'accessible_nouvelle_caledonie', type: 'boolean', title: 'Accessible en Nouvelle-Calédonie', description: 'Indique si la certification est accessible en Nouvelle-Calédonie.', extract: (f) => text(f, 'ACCESSIBLE_NOUVELLE_CALEDONIE') },
  { key: 'accessible_polynesie_francaise', type: 'boolean', title: 'Accessible en Polynésie française', description: 'Indique si la certification est accessible en Polynésie française.', extract: (f) => text(f, 'ACCESSIBLE_POLYNESIE_FRANCAISE') },
  { key: 'ccn_1_numero', type: 'string', title: 'CCN 1 — numéro', description: 'Numéro de brochure de la 1re convention collective nationale rattachée à la certification.', extract: (f) => directJoin(f, 'CCN_1', 'NUMERO') },
  { key: 'ccn_1_libelle', type: 'string', title: 'CCN 1 — libellé', description: 'Intitulé de la 1re convention collective nationale rattachée à la certification.', extract: (f) => directJoin(f, 'CCN_1', 'LIBELLE') },
  { key: 'ccn_2_numero', type: 'string', title: 'CCN 2 — numéro', description: 'Numéro de brochure de la 2e convention collective nationale rattachée à la certification.', extract: (f) => directJoin(f, 'CCN_2', 'NUMERO') },
  { key: 'ccn_2_libelle', type: 'string', title: 'CCN 2 — libellé', description: 'Intitulé de la 2e convention collective nationale rattachée à la certification.', extract: (f) => directJoin(f, 'CCN_2', 'LIBELLE') },
  { key: 'ccn_3_numero', type: 'string', title: 'CCN 3 — numéro', description: 'Numéro de brochure de la 3e convention collective nationale rattachée à la certification.', extract: (f) => directJoin(f, 'CCN_3', 'NUMERO') },
  { key: 'ccn_3_libelle', type: 'string', title: 'CCN 3 — libellé', description: 'Intitulé de la 3e convention collective nationale rattachée à la certification.', extract: (f) => directJoin(f, 'CCN_3', 'LIBELLE') },
  { key: 'codes_idcc', type: 'string', title: 'Codes IDCC', description: 'Codes IDCC (identifiant de convention collective) des branches professionnelles concernées.', separator: SEP, extract: (f) => itemsJoin(f, 'CODES_IDCC', 'IDCC', 'CODE') },
  { key: 'libelles_idcc', type: 'string', title: 'Libellés IDCC', description: 'Intitulés des conventions collectives correspondant aux codes IDCC.', separator: SEP, extract: (f) => itemsJoin(f, 'CODES_IDCC', 'IDCC', 'LIBELLE') },
  { key: 'siret_certificateurs', type: 'string', title: 'SIRET des certificateurs', description: 'Numéros SIRET des organismes certificateurs, alignés avec la colonne Certificateurs.', separator: SEP, extract: (f) => itemsJoin(f, 'CERTIFICATEURS', 'CERTIFICATEUR', 'SIRET_CERTIFICATEUR') },
  { key: 'annees_promotions_niveau', type: 'string', title: 'Années de promotions', description: 'Années de promotions auxquelles s’applique le niveau de qualification octroyé.', separator: SEP, extract: (f) => directJoin(f, 'ANNEES_PROMOTIONS_NIVEAU', 'ANNEE') },
  { key: 'blocs_competences_codes', type: 'string', title: 'Blocs de compétences (codes)', description: 'Codes des blocs de compétences (ensembles homogènes et cohérents de compétences) constituant la certification.', separator: SEP, extract: (f) => itemsJoin(f, 'BLOCS_COMPETENCES', 'BLOC_COMPETENCES', 'CODE') },
  { key: 'blocs_competences_libelles', type: 'string', title: 'Blocs de compétences (libellés)', description: 'Intitulés des blocs de compétences correspondant aux codes.', separator: SEP, extract: (f) => itemsJoin(f, 'BLOCS_COMPETENCES', 'BLOC_COMPETENCES', 'LIBELLE') },
  { key: 'partenaires', type: 'string', title: 'Partenaires', description: 'Raisons sociales des organismes partenaires habilités à préparer à la certification.', separator: SEP, extract: (f) => itemsJoin(f, 'PARTENAIRES', 'PARTENAIRE', 'NOM_PARTENAIRE') },
  { key: 'siret_partenaires', type: 'string', title: 'SIRET des partenaires', description: 'Numéros SIRET des organismes partenaires, alignés avec la colonne Partenaires.', separator: SEP, extract: (f) => itemsJoin(f, 'PARTENAIRES', 'PARTENAIRE', 'SIRET_PARTENAIRE') },
  { key: 'publication_decret_general', type: 'string', title: 'Textes réglementaires (général)', description: 'Textes réglementaires généraux encadrant la certification (date et titre de publication au JO/BO).', extract: (f) => publicationDecret(f, 'PUBLICATION_DECRET_GENERAL') },
  { key: 'publication_decret_creation', type: 'string', title: 'Textes réglementaires (création)', description: 'Arrêtés et décisions de création de la certification publiés au JO/BO (date et titre).', extract: (f) => publicationDecret(f, 'PUBLICATION_DECRET_CREATION') },
  { key: 'publication_decret_autre', type: 'string', title: 'Textes réglementaires (autres)', description: 'Autres textes réglementaires liés à la certification (date et titre de publication).', extract: (f) => publicationDecret(f, 'PUBLICATION_DECRET_AUTRE') },
  { key: 'statistiques_promotions', type: 'string', title: 'Statistiques des promotions', description: 'Statistiques par année de promotion : nombre de certifiés, nombre via VAE et taux d’insertion professionnelle (à 6 mois et 2 ans).', extract: (f) => statistiquesPromotions(f) },
  { key: 'date_de_publication', type: 'string', title: 'Date de publication', description: 'Date de première publication de la fiche au répertoire.', 'x-refersTo': 'http://schema.org/dateCreated', extract: (f) => text(f, 'DATE_DE_PUBLICATION') },
  { key: 'date_limite_delivrance', type: 'string', title: 'Date limite de délivrance', description: 'Date limite au-delà de laquelle la certification ne peut plus être délivrée, lorsqu’elle diffère de la date de fin d’enregistrement.', extract: (f) => text(f, 'DATE_LIMITE_DELIVRANCE') },
  { key: 'prerequis_entree_formation', type: 'string', title: 'Prérequis à l’entrée en formation', description: 'Conditions et prérequis exigés pour entrer dans le parcours de formation menant à la certification.', 'x-display': 'markdown', extract: (f) => richText(f, 'PREREQUIS_ENTREE_FORMATION') },
  { key: 'prerequis_validation_certification', type: 'string', title: 'Prérequis à la validation', description: 'Conditions et prérequis exigés pour valider et obtenir la certification.', 'x-display': 'markdown', extract: (f) => richText(f, 'PREREQUIS_VALIDATION_CERTIFICATION') },
  { key: 'nouvelles_certifications', type: 'string', title: 'Nouvelles certifications', description: 'Identifiants de fiche (ID_FICHE) des certifications qui remplacent celle-ci.', separator: SEP, extract: (f) => itemsJoin(f, 'NOUVELLES_CERTIFICATIONS', 'NOUVELLE_CERTIFICATION', 'ID_FICHE_NOUVELLE_CERTIFICATION') },
  { key: 'anciennes_certifications', type: 'string', title: 'Anciennes certifications', description: 'Identifiants de fiche (ID_FICHE) des certifications antérieures que celle-ci remplace.', separator: SEP, extract: (f) => itemsJoin(f, 'ANCIENNES_CERTIFICATIONS', 'ANCIENNE_CERTIFICATION', 'ID_FICHE_ANCIENNE_CERTIFICATION') },
  { key: 'correspondances', type: 'string', title: 'Correspondances', description: 'Équivalences reconnues entre blocs de compétences de cette certification et ceux d’autres certifications (format « source → fiche cible (bloc) »).', extract: (f) => correspondances(f) }
]

export const rncp: Repertoire = {
  code: 'RNCP',
  datasetTitle: 'Certifications RNCP',
  datasetDescription: DATASET_DESCRIPTION,
  datasetSummary: DATASET_SUMMARY,
  schema
}
